var = input("Digite algo: ")

print("O tipo primitivo desse valor é:", type(var))
print("Só tem espaços?", var.isspace())
print("É um número?", var.isnumeric())
print("É alfabético?", var.isalpha())
print("É um alfanumérico?", var.isalnum())
print("Está em maiúsculo?", var.isupper())
print("Está em minúsculo", var.islower())
print("Está capitalizada?", var.istitle())